In [2]:
import pandas as pd

# Load the Excel file
file_path = "All Data.xlsx"
data = pd.read_excel(file_path)

# Display the first few rows of the file
print(data.head())

          DisNo. Historic Classification Key Disaster Group Disaster Subgroup  \
0  1900-0003-USA      Yes    nat-met-sto-tro        Natural    Meteorological
1  1900-0006-JAM      Yes    nat-hyd-flo-flo        Natural      Hydrological
2  1900-0007-JAM      Yes    nat-bio-epi-vir        Natural        Biological
3  1900-0008-JPN      Yes    nat-geo-vol-ash        Natural       Geophysical
4  1900-0009-TUR      Yes    nat-geo-ear-gro        Natural       Geophysical

       Disaster Type  Disaster Subtype External IDs       Event Name  ISO  \
0              Storm  Tropical cyclone          NaN              NaN  USA
1              Flood   Flood (General)          NaN              NaN  JAM
2           Epidemic     Viral disease          NaN  Gastroenteritis  JAM
3  Volcanic activity          Ash fall          NaN              NaN  JPN
4         Earthquake   Ground movement          NaN              NaN  TUR

   ... Reconstruction Costs ('000 US$)  \
0  ...                             NaN
1  ...                             NaN
2  ...                             NaN
3  ...                             NaN
4  ...                             NaN

  Reconstruction Costs, Adjusted ('000 US$) Insured Damage ('000 US$)  \
0                                       NaN                       NaN
1                                       NaN                       NaN
2                                       NaN                       NaN
3                                       NaN                       NaN
4                                       NaN                       NaN

  Insured Damage, Adjusted ('000 US$) Total Damage ('000 US$)  \
0                                 NaN                 30000.0
1                                 NaN                     NaN
2                                 NaN                     NaN
3                                 NaN                     NaN
4                                 NaN                     NaN

  Total Damage, Adjusted ('000 US$)       CPI Admin Units  Entry Date  \
0                         1098720.0  2.730451         NaN  2004-10-18
1                               NaN  2.730451         NaN  2003-07-01
2                               NaN  2.730451         NaN  2003-07-01
3                               NaN  2.730451         NaN  2003-07-01
4                               NaN  2.730451         NaN  2019-08-05

   Last Update
0   2023-10-17
1   2023-09-25
2   2023-09-25
3   2023-09-25
4   2023-09-25

[5 rows x 46 columns]

In [3]:
# Create a new DataFrame by removing rows with NaN in specific columns
columns_to_check = ["Total Damage ('000 US$)", "Total Damage, Adjusted ('000 US$)"]
cleaned_data = data.dropna(subset=columns_to_check)

print("New DataFrame with rows containing NaN in specified columns removed:")
print(cleaned_data)

# Verify the changes
print(f"Original DataFrame shape: {data.shape}")
print(f"Cleaned DataFrame shape: {cleaned_data.shape}")

New DataFrame with rows containing NaN in specified columns removed:
              DisNo. Historic Classification Key Disaster Group  \
0      1900-0003-USA      Yes    nat-met-sto-tro        Natural
16     1902-0012-GTM      Yes    nat-geo-ear-gro        Natural
19     1903-0002-USA      Yes    nat-hyd-flo-flo        Natural
36     1905-0003-IND      Yes    nat-geo-ear-gro        Natural
40     1905-0008-ALB      Yes    nat-geo-ear-gro        Natural
...              ...      ...                ...            ...
16910  2023-0843-USA       No    nat-met-sto-sev        Natural
16929  2023-9234-ESP       No    nat-cli-dro-dro        Natural
16934  2023-9651-BRA       No    nat-cli-dro-dro        Natural
16936  2023-9868-USA       No    nat-cli-dro-dro        Natural
16937  2023-9872-CHN       No    nat-cli-dro-dro        Natural

      Disaster Subgroup Disaster Type  Disaster Subtype External IDs  \
0        Meteorological         Storm  Tropical cyclone          NaN
16          Geophysical    Earthquake   Ground movement          NaN
19         Hydrological         Flood   Flood (General)          NaN
36          Geophysical    Earthquake   Ground movement          NaN
40          Geophysical    Earthquake   Ground movement          NaN
...                 ...           ...               ...          ...
16910    Meteorological         Storm    Severe weather          NaN
16929    Climatological       Drought           Drought          NaN
16934    Climatological       Drought           Drought          NaN
16936    Climatological       Drought           Drought          NaN
16937    Climatological       Drought           Drought          NaN

      Event Name  ISO  ... Reconstruction Costs ('000 US$)  \
0            NaN  USA  ...                             NaN
16           NaN  GTM  ...                             NaN
19           NaN  USA  ...                             NaN
36           NaN  IND  ...                             NaN
40           NaN  ALB  ...                             NaN
...          ...  ...  ...                             ...
16910        NaN  USA  ...                             NaN
16929        NaN  ESP  ...                             NaN
16934        NaN  BRA  ...                             NaN
16936        NaN  USA  ...                             NaN
16937        NaN  CHN  ...                             NaN

      Reconstruction Costs, Adjusted ('000 US$) Insured Damage ('000 US$)  \
0                                           NaN                       NaN
16                                          NaN                       NaN
19                                          NaN                       NaN
36                                          NaN                       NaN
40                                          NaN                       NaN
...                                         ...                       ...
16910                                       NaN                       NaN
16929                                       NaN                  300000.0
16934                                       NaN                       NaN
16936                                       NaN                       NaN
16937                                       NaN                       NaN

      Insured Damage, Adjusted ('000 US$) Total Damage ('000 US$)  \
0                                     NaN                 30000.0
16                                    NaN                 25000.0
19                                    NaN                480000.0
36                                    NaN                 25000.0
40                                    NaN                 23800.0
...                                   ...                     ...
16910                                 NaN               1300000.0
16929                            300000.0               2400000.0
16934                                 NaN               2500000.0
16936                                 NaN              14500000.0
16937                                 NaN               2700000.0

      Total Damage, Adjusted ('000 US$)         CPI  \
0                             1098720.0    2.730451
16                             880384.0    2.839669
19                           16277328.0    2.948887
36                             847777.0    2.948887
40                             807084.0    2.948887
...                                 ...         ...
16910                         1300000.0  100.000000
16929                         2400000.0  100.000000
16934                         2500000.0  100.000000
16936                        14500000.0  100.000000
16937                         2700000.0  100.000000

                                             Admin Units  Entry Date  \
0                                                    NaN  2004-10-18
16                                                   NaN  2003-07-01
19                                                   NaN  2003-07-01
36                                                   NaN  2003-07-01
40                                                   NaN  2019-08-06
...                                                  ...         ...
16910                                                NaN  2023-12-19
16929  [{"adm1_code":2716,"adm1_name":"Andalucía"},{"...  2023-04-19
16934                                                NaN  2023-10-11
16936                                                NaN  2024-01-17
16937                                                NaN  2024-02-12

       Last Update
0       2023-10-17
16      2023-09-25
19      2023-09-25
36      2023-09-25
40      2023-09-25
...            ...
16910   2024-02-28
16929   2024-02-09
16934   2024-01-26
16936   2024-02-27
16937   2024-03-04

[5465 rows x 46 columns]
Original DataFrame shape: (17294, 46)
Cleaned DataFrame shape: (5465, 46)

In [4]:
print(f"Shape of the DataFrame: {data.shape}")
print("Column names:", data.columns.tolist())
print("Data types:\n", data.dtypes)

Shape of the DataFrame: (17294, 46)
Column names: ['DisNo.', 'Historic', 'Classification Key', 'Disaster Group', 'Disaster Subgroup', 'Disaster Type', 'Disaster Subtype', 'External IDs', 'Event Name', 'ISO', 'Country', 'Subregion', 'Region', 'Location', 'Origin', 'Associated Types', 'OFDA/BHA Response', 'Appeal', 'Declaration', "AID Contribution ('000 US$)", 'Magnitude', 'Magnitude Scale', 'Latitude', 'Longitude', 'River Basin', 'Start Year', 'Start Month', 'Start Day', 'End Year', 'End Month', 'End Day', 'Total Deaths', 'No. Injured', 'No. Affected', 'No. Homeless', 'Total Affected', "Reconstruction Costs ('000 US$)", "Reconstruction Costs, Adjusted ('000 US$)", "Insured Damage ('000 US$)", "Insured Damage, Adjusted ('000 US$)", "Total Damage ('000 US$)", "Total Damage, Adjusted ('000 US$)", 'CPI', 'Admin Units', 'Entry Date', 'Last Update']
Data types:
 DisNo.                                        object
Historic                                      object
Classification Key                            object
Disaster Group                                object
Disaster Subgroup                             object
Disaster Type                                 object
Disaster Subtype                              object
External IDs                                  object
Event Name                                    object
ISO                                           object
Country                                       object
Subregion                                     object
Region                                        object
Location                                      object
Origin                                        object
Associated Types                              object
OFDA/BHA Response                             object
Appeal                                        object
Declaration                                   object
AID Contribution ('000 US$)                  float64
Magnitude                                    float64
Magnitude Scale                               object
Latitude                                     float64
Longitude                                    float64
River Basin                                   object
Start Year                                     int64
Start Month                                  float64
Start Day                                    float64
End Year                                       int64
End Month                                    float64
End Day                                      float64
Total Deaths                                 float64
No. Injured                                  float64
No. Affected                                 float64
No. Homeless                                 float64
Total Affected                               float64
Reconstruction Costs ('000 US$)              float64
Reconstruction Costs, Adjusted ('000 US$)    float64
Insured Damage ('000 US$)                    float64
Insured Damage, Adjusted ('000 US$)          float64
Total Damage ('000 US$)                      float64
Total Damage, Adjusted ('000 US$)            float64
CPI                                          float64
Admin Units                                   object
Entry Date                                    object
Last Update                                   object
dtype: object

In [ ]:
import pandas as pd

# Assuming 'df' is your DataFrame
# Get the statistical summary for all numerical columns
numerical_cols = data.select_dtypes(include='number')  
summary = numerical_cols.describe().transpose() 

# Display the summary
print(summary)

                                             count          mean  \
AID Contribution ('000 US$)                  776.0  2.003959e+04
Magnitude                                   5132.0  3.826778e+04
Latitude                                    2798.0  1.852940e+01
Longitude                                   2798.0  3.947985e+01
Start Year                                 17294.0  1.998910e+03
Start Month                                16899.0  6.463519e+00
Start Day                                  13594.0  1.524893e+01
End Year                                   17294.0  1.998964e+03
End Month                                  16591.0  6.616358e+00
End Day                                    13682.0  1.577935e+01
Total Deaths                               12345.0  2.647302e+03
No. Injured                                 4409.0  2.445594e+03
No. Affected                               10192.0  8.493382e+05
No. Homeless                                2498.0  7.158232e+04
Total Affected                             12702.0  6.964297e+05
Reconstruction Costs ('000 US$)               40.0  5.572706e+06
Reconstruction Costs, Adjusted ('000 US$)     40.0  6.897185e+06
Insured Damage ('000 US$)                   1134.0  9.224431e+05
Insured Damage, Adjusted ('000 US$)         1120.0  1.305815e+06
Total Damage ('000 US$)                     5517.0  8.296174e+05
Total Damage, Adjusted ('000 US$)           5465.0  1.322311e+06
CPI                                        16941.0  5.708081e+01

                                                    std          min  \
AID Contribution ('000 US$)                1.690305e+05     1.000000
Magnitude                                  2.347156e+05   -57.000000
Latitude                                   2.159856e+01   -72.640000
Longitude                                  7.736177e+01  -178.252000
Start Year                                 2.058929e+01  1900.000000
Start Month                                3.387142e+00     1.000000
Start Day                                  8.958899e+00     1.000000
End Year                                   2.057681e+01  1900.000000
End Month                                  3.355213e+00     1.000000
End Day                                    8.876706e+00     1.000000
Total Deaths                               6.597115e+04     1.000000
No. Injured                                3.245894e+04     1.000000
No. Affected                               8.190830e+06     1.000000
No. Homeless                               5.160414e+05     3.000000
Total Affected                             7.413411e+06     1.000000
Reconstruction Costs ('000 US$)            1.624858e+07    84.000000
Reconstruction Costs, Adjusted ('000 US$)  1.738285e+07   131.000000
Insured Damage ('000 US$)                  3.678694e+06    34.000000
Insured Damage, Adjusted ('000 US$)        4.924794e+06    48.000000
Total Damage ('000 US$)                    5.048992e+06     2.000000
Total Damage, Adjusted ('000 US$)          7.259816e+06     3.000000
CPI                                        2.448322e+01     2.730451

                                                    25%            50%  \
AID Contribution ('000 US$)                  174.750000     724.500000
Magnitude                                      6.900000     144.000000
Latitude                                       3.295000      22.970000
Longitude                                     -0.232500      49.194500
Start Year                                  1990.000000    2003.000000
Start Month                                    4.000000       7.000000
Start Day                                      7.000000      15.000000
End Year                                    1990.000000    2003.000000
End Month                                      4.000000       7.000000
End Day                                        8.000000      16.000000
Total Deaths                                   6.000000      18.000000
No. Injured                                   12.000000      50.000000
No. Affected                                1276.500000   10001.000000
No. Homeless                                 500.000000    3000.000000
Total Affected                               677.250000    6000.000000
Reconstruction Costs ('000 US$)            64375.000000  444500.000000
Reconstruction Costs, Adjusted ('000 US$)  99240.000000  537547.500000
Insured Damage ('000 US$)                  50000.000000  175000.000000
Insured Damage, Adjusted ('000 US$)        95986.250000  268331.000000
Total Damage ('000 US$)                    10000.000000   68000.000000
Total Damage, Adjusted ('000 US$)          19196.000000  132713.000000
CPI                                           42.880732      59.033144

                                                    75%           max
AID Contribution ('000 US$)                3.669750e+03  3.518530e+06
Magnitude                                  8.000000e+03  1.302587e+07
Latitude                                   3.652860e+01  6.793000e+01
Longitude                                  1.027930e+02  1.796500e+02
Start Year                                 2.013750e+03  2.024000e+03
Start Month                                9.000000e+00  1.200000e+01
Start Day                                  2.300000e+01  3.100000e+01
End Year                                   2.014000e+03  2.024000e+03
End Month                                  9.000000e+00  1.200000e+01
End Day                                    2.375000e+01  3.100000e+01
Total Deaths                               6.100000e+01  3.700000e+06
No. Injured                                2.000000e+02  1.800000e+06
No. Affected                               9.500000e+04  3.300000e+08
No. Homeless                               1.641525e+04  1.585000e+07
Total Affected                             6.000000e+04  3.300000e+08
Reconstruction Costs ('000 US$)            3.808000e+06  1.000000e+08
Reconstruction Costs, Adjusted ('000 US$)  5.389496e+06  1.000000e+08
Insured Damage ('000 US$)                  5.475000e+05  6.000000e+07
Insured Damage, Adjusted ('000 US$)        8.438538e+05  9.361435e+07
Total Damage ('000 US$)                    3.630000e+05  2.100000e+08
Total Damage, Adjusted ('000 US$)          6.613010e+05  2.844652e+08
CPI                                        7.645415e+01  1.000000e+02

In [ ]:
summary

,count,mean,std,min,25%,50%,75%,max
AID Contribution ('000 US$),776.0,2.003959e+04,1.690305e+05,1.000000,174.750000,724.500000,3.669750e+03,3.518530e+06
Magnitude,5132.0,3.826778e+04,2.347156e+05,-57.000000,6.900000,144.000000,8.000000e+03,1.302587e+07
Latitude,2798.0,1.852940e+01,2.159856e+01,-72.640000,3.295000,22.970000,3.652860e+01,6.793000e+01
Longitude,2798.0,3.947985e+01,7.736177e+01,-178.252000,-0.232500,49.194500,1.027930e+02,1.796500e+02
Start Year,17294.0,1.998910e+03,2.058929e+01,1900.000000,1990.000000,2003.000000,2.013750e+03,2.024000e+03
Start Month,16899.0,6.463519e+00,3.387142e+00,1.000000,4.000000,7.000000,9.000000e+00,1.200000e+01
Start Day,13594.0,1.524893e+01,8.958899e+00,1.000000,7.000000,15.000000,2.300000e+01,3.100000e+01
End Year,17294.0,1.998964e+03,2.057681e+01,1900.000000,1990.000000,2003.000000,2.014000e+03,2.024000e+03
End Month,16591.0,6.616358e+00,3.355213e+00,1.000000,4.000000,7.000000,9.000000e+00,1.200000e+01
End Day,13682.0,1.577935e+01,8.876706e+00,1.000000,8.000000,16.000000,2.375000e+01,3.100000e+01
Total Deaths,12345.0,2.647302e+03,6.597115e+04,1.000000,6.000000,18.000000,6.100000e+01,3.700000e+06
No. Injured,4409.0,2.445594e+03,3.245894e+04,1.000000,12.000000,50.000000,2.000000e+02,1.800000e+06
No. Affected,10192.0,8.493382e+05,8.190830e+06,1.000000,1276.500000,10001.000000,9.500000e+04,3.300000e+08
No. Homeless,2498.0,7.158232e+04,5.160414e+05,3.000000,500.000000,3000.000000,1.641525e+04,1.585000e+07
Total Affected,12702.0,6.964297e+05,7.413411e+06,1.000000,677.250000,6000.000000,6.000000e+04,3.300000e+08
Reconstruction Costs ('000 US$),40.0,5.572706e+06,1.624858e+07,84.000000,64375.000000,444500.000000,3.808000e+06,1.000000e+08
"Reconstruction Costs, Adjusted ('000 US$)",40.0,6.897185e+06,1.738285e+07,131.000000,99240.000000,537547.500000,5.389496e+06,1.000000e+08
Insured Damage ('000 US$),1134.0,9.224431e+05,3.678694e+06,34.000000,50000.000000,175000.000000,5.475000e+05,6.000000e+07
"Insured Damage, Adjusted ('000 US$)",1120.0,1.305815e+06,4.924794e+06,48.000000,95986.250000,268331.000000,8.438538e+05,9.361435e+07
Total Damage ('000 US$),5517.0,8.296174e+05,5.048992e+06,2.000000,10000.000000,68000.000000,3.630000e+05,2.100000e+08
"Total Damage, Adjusted ('000 US$)",5465.0,1.322311e+06,7.259816e+06,3.000000,19196.000000,132713.000000,6.613010e+05,2.844652e+08
CPI,16941.0,5.708081e+01,2.448322e+01,2.730451,42.880732,59.033144,7.645415e+01,1.000000e+02

: